server:
  port: 8081
  
spring:
  application:
    name: ms-BankAccount
  datasource:
    url: jdbc:h2:mem:account-db
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  graphql:
    graphiql:
      enabled: true



